import {
    Cpu,
    Server,
    HardDrive,
    Router,
    Network,
    Activity,
    Zap,
    Gauge,
    Sliders,
    Terminal,
    Radio,
    Tv,
    Smartphone,
    Tablet,
    Printer,
    Camera,
    Microchip,
    Database,
    Shield,
    Power,
    BatteryCharging,
} from "lucide-react";

export const LogoMap = {
    cpu: Cpu,
    server: Server,
    hardDrive: HardDrive,
    router: Router,
    network: Network,
    microchip: Microchip,

    activity: Activity,
    gauge: Gauge,
    zap: Zap,
    sliders: Sliders,
    radio: Radio,
    terminal: Terminal,

    database: Database,
    printer: Printer,
    camera: Camera,
    smartphone: Smartphone,
    tablet: Tablet,
    tv: Tv,

    power: Power,
    battery: BatteryCharging,
    shield: Shield,
};